---
settings:
  name: EDA workloads
  internal:
    pdf_enabled: true
    termcheck_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: zh-tw,us-en,de-de,es-es,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn
sidebar:
  entries:
  - title: EDA 工作負載文檔
    url: "/index.html"
  - title: 發行說明
    entries:
    - title: 什麼是新的
      url: "/whats-new.html"
    - title: 已知限制
      url: "/known-limitations.html"
  - title: 開始使用
    entries:
    - title: 了解NetApp Workload Factory for EDA
      url: "/learn-eda.html"
    - title: 快速啟動
      url: "/quick-start-eda.html"
    - title: 要求
      url: "/requirements-eda.html"
  - title: EDA 儲存概述
    entries:
    - title: 了解概覽儀表板
      url: "/learn-overview-dashboard.html"
    - title: 啟動 Overview 儀表板
      url: "/task-activate-overview-dashboard.html"
    - title: 使用概覽儀表板
      url: "/task-use-overview-dashboard.html"
  - title: FSx for ONTAP 延遲分析
    entries:
    - title: 了解延遲監控
      url: "/learn-latency-monitoring.html"
    - title: 設定延遲監控
      url: "/task-configure-latency-monitoring.html"
    - title: 分析延遲問題
      url: "/task-analyze-latency-issues.html"
    - title: 分析延遲趨勢
      url: "/task-analyze-latency-trends.html"
  - title: 專案使用分析
    entries:
    - title: 了解專案儀表板
      url: "/learn-project-dashboard.html"
    - title: 設定專案儀表板
      url: "/task-configure-project-dashboard.html"
    - title: 使用 Projects 儀表板
      url: "/task-use-project-dashboard.html"
  - title: 使用 Perforce 集成
    entries:
    - title: 了解 Perforce 集成
      url: "/learn-eda-workloads.html"
    - title: 專案管理
      url: "/manage-projects.html"
    - title: 管理專案版本
      url: "/version-projects.html"
    - title: 建立工作區
      url: "/create-workspaces.html"
    - title: 使用 Codebox 實現自動化
      url: "/automate-codebox.html"
    - title: 與 Perforce 集成
      url: "/integrate-perforce.html"
  - title: 知識和支持
    entries:
    - title: 註冊以獲得支持
      url: "/support-registration.html"
    - title: 獲取協助
      url: "/get-help-eda.html"
  - title: 法律聲明
    url: "/legal-notices.html"
product-family:
  name: NetApp Workload Factory
  repo: workload-family
